name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build and publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Create zip for HACS
        run: |
          cd custom_components
          zip -r ../somfy_rts.zip somfy_rts/

      - name: Upload release assets
        uses: softprops/action-gh-release@v3
        with:
          files: somfy_rts.zip
          generate_release_notes: true